import random

"""
Passcode Generator
==================
DO NOT change any of this without understanding the tradeoffs below.

Format:     WordWordWordWordWordNN  (5 title-cased words + 2-digit number, no separator)
Example:    RiverForestCrystalStormFalcon42
Word list:  1,668 words, manually curated — no profanity, slurs, or offensive terms.
Entropy:    ~57 bits  (1668^5 * 90 = ~1.16 x 10^17 combinations)
Equivalent: ~9.5-char random alphanumeric.

Why this exists
---------------
Students CANNOT change their passcode — the LDAP system has no password
change feature. This passcode is permanent for the student's entire enrollment.
Word-based format is the only way to make a 30+ char credential
memorable enough that students don't write it on a sticky note.

Design decisions & tradeoffs
----------------------------
- 5 words not 4: 4 words + 1 digit (~26 bits, original design) is too weak
  for a permanent credential. 57 bits is adequate for offline cracking
  resistance — it costs real GPU time to crack even one hash.
- 5 words not 6+: 6+ words pushes passcodes past 40 characters and causes
  typing errors. Already at ~30-40 chars with 5 words.
- 2-digit number not 1-digit: Adds 9x more combinations (90 vs 9) for 1 char.
- No separator (hyphen/dot): Deliberate product decision, don't add one.
- No special chars: Would make passcodes harder to type (students on phones,
  kiosks, etc.) with marginal entropy gain.
- `random` not `secrets`: Passcodes are generated offline in batch, not in
  a web request. If this ever shifts to on-the-fly generation, switch to
  `secrets.SystemRandom()`.

What this does NOT protect against
-----------------------------------
- Phishing, keyloggers, physical passcode handout theft.
- Students reusing the same passcode on other services.
- Anything outside this codebase (LDAP lockout policy, MFA, network security,
  baseline CSV access controls).

If the repo ever goes public
----------------------------
The word list secrecy is NOT the entropy source (Kerckhoffs's principle).
1668^5 * 90 = ~57 bits regardless of whether the attacker knows the list.
If you want more paranoia, add a PASSCODE_WORD_FILE env var that overrides
the embedded list with a private file.

Word list maintenance
---------------------
DO NOT add words without reviewing for:
- Offensive/insensitive meanings (including in other dialects of English).
- Inappropriate acronyms when concatenated.
- Obscurity — the word must be recognizable to a typical 18-year-old.
- Adding words increases entropy (log2(n) per word). Removing words or
  reducing word count directly reduces security.
"""

WORDS = [
    "Abacus", "Abbey", "Acorn", "Admiral", "Agate", "Albatross", "Alchemy",
    "Alpine", "Amber", "Anchor", "Anemone", "Angel", "Anvil", "Apricot",
    "Arbor", "Arcade", "Archer", "Archway", "Arctic", "Arena", "Arrow",
    "Artisan", "Aspen", "Atlas", "Aurora", "Autumn", "Avenue",
    "Badge", "Badger", "Bamboo", "Bandit", "Banner", "Barbell", "Bard",
    "Barrel", "Basalt", "Basin", "Basket", "Bastion", "Bayou", "Beach",
    "Bead", "Beacon", "Beam", "Bean", "Bear", "Beaver", "Bedrock",
    "Beech", "Beetle", "Bell", "Belt", "Bench", "Birch", "Bishop",
    "Bison", "Blade", "Blanket", "Blaze", "Blizzard", "Block", "Bloom",
    "Blossom", "Bluff", "Board", "Boar", "Boat", "Bolt", "Bonfire",
    "Bone", "Book", "Boot", "Boulder", "Bouquet", "Bowl", "Brace",
    "Bracket", "Braid", "Branch", "Brand", "Breeze", "Brick", "Bridge",
    "Brim", "Bristle", "Bronze", "Brook", "Broom", "Brush", "Bubble",
    "Buck", "Bucket", "Buckler", "Buffalo", "Bugle", "Bulb", "Bull",
    "Bullet", "Bumper", "Bundle", "Burden", "Bureau", "Burnish",
    "Burrow", "Burst", "Bush", "Butter", "Button", "Buzz",
    "Cabin", "Cable", "Cactus", "Cafe", "Cage", "Caldera", "Calf",
    "Camel", "Camera", "Camp", "Canal", "Candle", "Candy", "Cane",
    "Canopy", "Canyon", "Cape", "Captain", "Caravan", "Carbon", "Card",
    "Cardinal", "Cargo", "Carnival", "Carpet", "Carrot", "Cart",
    "Castle", "Cattle", "Cave", "Cedar", "Celery", "Cello",
    "Cement", "Ceramic", "Cereal", "Chain", "Chair", "Chalk",
    "Chamber", "Champion", "Channel", "Chapel", "Charge", "Charm",
    "Chart", "Cheese", "Cherry", "Chest", "Chick", "Chill",
    "Chime", "Chip", "Chisel", "Chocolate", "Chorus", "Chrome",
    "Cider", "Cinder", "Circle", "Circuit", "Citadel", "City",
    "Clam", "Clasp", "Clay", "Cleat", "Cleft", "Cliff",
    "Climate", "Climb", "Clock", "Cloth", "Cloud", "Clover",
    "Club", "Coast", "Cobalt", "Cobra", "Cocoa", "Code",
    "Coffee", "Coil", "Coin", "Collar", "Colony", "Column",
    "Comb", "Comet", "Compass", "Cone", "Copper", "Coral",
    "Cord", "Core", "Cork", "Corn", "Corner", "Corridor",
    "Cosmos", "Cottage", "Cotton", "Couch", "Council", "Course",
    "Court", "Cove", "Cradle", "Craft", "Crane", "Crater",
    "Crayon", "Cream", "Creek", "Crest", "Cricket", "Crisp",
    "Crop", "Cross", "Crow", "Crown", "Cruise", "Crust",
    "Crystal", "Cub", "Cup", "Cupboard", "Cure", "Curtain",
    "Curve", "Cushion", "Cycle", "Cypress",
    "Dagger", "Dairy", "Daisy", "Dam", "Dance", "Dandelion",
    "Dart", "Dash", "Dawn", "Deer", "Delta", "Denim",
    "Desert", "Design", "Desk", "Dew", "Dial", "Diamond",
    "Diary", "Diesel", "Dill", "Dime", "Diner", "Dingo",
    "Dinner", "Diploma", "Dirt", "Disc", "Dish", "Dock",
    "Domain", "Dome", "Door", "Dove", "Draft", "Dragon",
    "Drain", "Drama", "Dream", "Dress", "Drift", "Drill",
    "Drink", "Drive", "Drone", "Drop", "Drum", "Duck",
    "Duct", "Dune", "Dungeon", "Dusk", "Dust", "Duty",
    "Dwarf", "Dynamo",
    "Eagle", "Earl", "Earth", "Echo", "Eclipse", "Edge",
    "Elbow", "Elder", "Elk", "Elm", "Ember", "Emblem",
    "Emerald", "Empire", "Engine", "Ensign", "Epic", "Epoch",
    "Equator", "Equinox", "Estate", "Eternity",
    "Evening", "Everest", "Expanse", "Explorer",
    "Fable", "Fabric", "Facet", "Falcon", "Fang", "Fantasy",
    "Farm", "Fate", "Fawn", "Feast", "Feather", "Fence",
    "Fern", "Ferret", "Ferry", "Festival", "Fiber",
    "Fiddle", "Field", "Fig", "Finch", "Fir", "Fire",
    "Fish", "Flag", "Flame", "Flamingo", "Flare", "Flash",
    "Flask", "Flavor", "Flax", "Fleet", "Flint", "Float",
    "Flock", "Flood", "Floor", "Flora", "Flour", "Flow",
    "Flower", "Flute", "Flux", "Foam", "Focus", "Fog",
    "Foil", "Fold", "Forest", "Forge", "Fork", "Form",
    "Fort", "Fortune", "Fossil", "Fountain", "Fox",
    "Frame", "Freckle", "Freeze", "Fresco",
    "Frost", "Fruit", "Fuel", "Furnace", "Fuse", "Fusion",
    "Future",
    "Galaxy", "Gale", "Game", "Garage", "Garden", "Garland",
    "Garnet", "Gate", "Gauge", "Gear", "Gem", "Genesis",
    "Geode", "Geyser", "Ghost", "Giant", "Gibbon",
    "Ginger", "Giraffe", "Glacier", "Glade", "Glare",
    "Glass", "Gleam", "Glen", "Glide", "Glint", "Globe",
    "Glory", "Glove", "Glow", "Glyph", "Gnome",
    "Goat", "Goblet", "Gold", "Golden", "Gondola", "Gong",
    "Goose", "Gorge", "Gorilla", "Gown", "Grace",
    "Grain", "Granite", "Grape", "Grass", "Grate",
    "Gravel", "Grave", "Gravity", "Grease", "Green",
    "Grid", "Grill", "Grind", "Grip", "Grit",
    "Groove", "Ground", "Grove", "Growth", "Grudge",
    "Guard", "Guest", "Guide", "Guild", "Guitar",
    "Gulf", "Gull", "Gust", "Gutter",
    "Habitat", "Hail", "Hammer", "Hammock", "Hamster",
    "Hand", "Handle", "Harbor", "Hare", "Harp",
    "Harvest", "Haven", "Hawk", "Hazard", "Haze",
    "Hazel", "Hearth", "Heath", "Heaven", "Hedge",
    "Helix", "Helmet", "Herb", "Herd", "Hero",
    "Heron", "Hickory", "Hide", "Highway", "Hike",
    "Hill", "Hilt", "Hinge", "Hive", "Hobby",
    "Hog", "Hold", "Hole", "Holiday", "Holly",
    "Home", "Honey", "Hood", "Hoop", "Horizon",
    "Horn", "Horse", "Hose", "Hound", "House",
    "Hover", "Hub", "Hull", "Humble", "Humor",
    "Hundred", "Hunger", "Hunt", "Hurdle", "Hurricane",
    "Hut", "Hybrid", "Hydrant",
    "Ice", "Icon", "Igloo", "Ignite", "Iguana",
    "Image", "Impact", "Impulse", "Indigo", "Infant",
    "Ink", "Inlet", "Inn", "Insect", "Iris",
    "Iron", "Island", "Isle", "Ivory", "Ivy",
    "Jacket", "Jade", "Jaguar", "Jar", "Jasmine",
    "Jaw", "Jazz", "Jelly", "Jersey", "Jewel",
    "Jingle", "Jockey", "Join", "Joint", "Joke",
    "Journal", "Journey", "Joy", "Judge", "Juice",
    "Jumble", "Jungle", "Juniper", "Justice",
    "Kangaroo", "Kayak", "Keeper", "Kelp", "Kernel",
    "Kestrel", "Kettle", "Key", "Kick", "Kind",
    "King", "Kingdom", "Kit", "Kitchen", "Kite",
    "Kitten", "Kiwi", "Knight", "Knob", "Knot",
    "Koala", "Koi",
    "Label", "Lace", "Ladder", "Lagoon", "Lake",
    "Lamb", "Lamp", "Lance", "Land", "Lane",
    "Lantern", "Laptop", "Larch", "Lark", "Laser",
    "Latch", "Lathe", "Lava", "Lavender", "Lawn",
    "Layer", "Lead", "Leaf", "League", "Leap",
    "Leather", "Legend", "Lemon", "Lens", "Leopard",
    "Letter", "Level", "Lever", "Liberty", "Lid",
    "Life", "Lift", "Light", "Lilac", "Lily",
    "Line", "Linen", "Link", "Lion", "Liquid",
    "Litter", "Lizard", "Llama", "Loaf", "Lobby",
    "Lobster", "Lock", "Locker", "Locust", "Lodge",
    "Loft", "Logic", "Lone", "Loop", "Loot",
    "Lord", "Lore", "Lounge", "Love", "Loyal",
    "Luck", "Lumber", "Lump", "Lunch", "Lung",
    "Lure", "Lynx", "Lyric",
    "Macaw", "Magnet", "Maid", "Mail", "Mallow",
    "Mammoth", "Mango", "Manor", "Mansion", "Mantle",
    "Map", "Maple", "Marble", "Mare", "Marina",
    "Mark", "Market", "Marlin", "Marmot", "Marquee",
    "Marrow", "Marsh", "Mascot", "Mask", "Mason",
    "Mast", "Master", "Match", "Mate", "Matrix",
    "Meadow", "Meal", "Medal", "Melody", "Melon",
    "Melt", "Memory", "Menu", "Mercy", "Merge",
    "Merit", "Mesh", "Metal", "Meteor", "Method",
    "Mice", "Mile", "Milk", "Mill", "Mimic",
    "Mind", "Mine", "Mineral", "Mink", "Mint",
    "Mirror", "Mist", "Mix", "Mobile", "Model",
    "Module", "Mold", "Mole", "Moment", "Money",
    "Monitor", "Monk", "Monkey", "Month", "Monument",
    "Mood", "Moon", "Moose", "Mosaic", "Mosque",
    "Moss", "Motor", "Motto", "Mound", "Mount",
    "Mountain", "Mouse", "Mouth", "Movie", "Mud",
    "Mule", "Mural", "Museum", "Mush", "Music",
    "Mussel", "Mustard", "Mystery", "Myth",
    "Nail", "Name", "Nap", "Nation", "Nature",
    "Navel", "Neck", "Need", "Needle", "Neon",
    "Nerve", "Nest", "Net", "Neuron", "Newt",
    "Niche", "Night", "Noble", "Node", "Noise",
    "Nomad", "Noodle", "Noon", "North", "Nose",
    "Notch", "Note", "Noun", "Novel", "Nugget",
    "Number", "Nurse", "Nut", "Nylon",
    "Oak", "Oar", "Oasis", "Oath", "Obelisk",
    "Ocean", "Ocelot", "Octopus", "Oil", "Olive",
    "Omen", "Onion", "Opal", "Opera", "Oracle",
    "Orange", "Orbit", "Orchard", "Order", "Organ",
    "Origin", "Ornament", "Osprey", "Ostrich", "Otter",
    "Oval", "Oven", "Owl", "Owner", "Oxygen",
    "Oyster",
    "Pace", "Pack", "Package", "Pad", "Paddle",
    "Page", "Pail", "Paint", "Pair", "Palace",
    "Palm", "Pan", "Panda", "Panel", "Panther",
    "Paper", "Parade", "Parasol", "Parcel", "Park",
    "Parrot", "Parsley", "Partner", "Party", "Pass",
    "Pasta", "Paste", "Pastel", "Path", "Patron",
    "Pattern", "Pause", "Paw", "Pawn", "Peace",
    "Peach", "Peak", "Peanut", "Pear", "Pearl",
    "Pebble", "Pecan", "Pedal", "Pelican", "Pen",
    "Pencil", "Penny", "Pepper", "Perch", "Period",
    "Petal", "Petrol", "Phantom", "Phase", "Phone",
    "Photo", "Piano", "Pick", "Pickle", "Picnic",
    "Picture", "Pie", "Piece", "Pigeon", "Pike",
    "Pile", "Pill", "Pillar", "Pillow", "Pilot",
    "Pin", "Pinch", "Pine", "Pink", "Pioneer",
    "Pipe", "Pirate", "Pistol", "Piston", "Pitch",
    "Pivot", "Pixel", "Pizza", "Place", "Plain",
    "Plan", "Plane", "Planet", "Plank", "Plant",
    "Plaster", "Plate", "Platform", "Platinum", "Platter",
    "Pledge", "Plow", "Plug", "Plum", "Plume",
    "Plunge", "Pocket", "Poem", "Poet", "Point",
    "Poker", "Polar", "Pole", "Polka", "Pollen",
    "Pond", "Pony", "Pool", "Poppy", "Porch",
    "Pork", "Port", "Portal", "Post", "Poster",
    "Pot", "Potato", "Potion", "Pouch", "Pound",
    "Powder", "Power", "Prairie", "Prawn", "Press",
    "Pride", "Prime", "Prince", "Prism", "Prize",
    "Probe", "Profit", "Prose", "Protein", "Pulse",
    "Pump", "Pumpkin", "Punch", "Puppet", "Puppy",
    "Purple", "Purse", "Puzzle", "Pyramid", "Python",
    "Quail", "Quake", "Quarry", "Quartz", "Quest",
    "Quill", "Quilt", "Quota", "Quote",
    "Rabbit", "Raccoon", "Race", "Rack", "Radar",
    "Radish", "Radius", "Raft", "Rage", "Raid",
    "Rail", "Rain", "Rainbow", "Rake", "Rally",
    "Ramp", "Ranch", "Range", "Ranger", "Rank",
    "Rat", "Raven", "Ray", "Razor", "Reach",
    "Realm", "Reaper", "Reason", "Record", "Reed",
    "Reef", "Reel", "Refuge", "Regal", "Reign",
    "Relay", "Relief", "Relish", "Remedy", "Remote",
    "Rental", "Repair", "Report", "Rescue", "Resort",
    "Rest", "Result", "Retail", "Retreat", "Return",
    "Reveal", "Revenge", "Reverse", "Review", "Reward",
    "Rhino", "Rhythm", "Ribbon", "Rice", "Ride",
    "Ridge", "Rifle", "Ring", "Rinse", "Ripple",
    "Rise", "Risk", "Ritual", "Rival", "River",
    "Road", "Roam", "Roar", "Roast", "Robin",
    "Robot", "Rock", "Rocket", "Rod", "Role",
    "Roll", "Roof", "Room", "Root", "Rope",
    "Rose", "Route", "Rover", "Royal", "Rubber",
    "Ruby", "Rudder", "Rug", "Ruin", "Rule",
    "Ruler", "Rush", "Rust", "Rustic", "Rye",
    "Sable", "Sabre", "Sack", "Saddle", "Safe",
    "Saga", "Sage", "Sail", "Sailor", "Saint",
    "Salad", "Salami", "Salmon", "Salon", "Salt",
    "Salute", "Sample", "Sand", "Sapphire", "Satchel",
    "Satin", "Sauce", "Saucer", "Savior", "Scale",
    "Scarf", "Scene", "Scent", "Scepter", "Scheme",
    "Scholar", "School", "Scissors", "Scoop", "Scope",
    "Score", "Scout", "Scrap", "Screen", "Scroll",
    "Scrub", "Sculpt", "Sea", "Seal", "Seam",
    "Season", "Seat", "Secret", "Section", "Seed",
    "Segment", "Select", "Senate", "Sense", "Sensor",
    "Sentry", "Sequel", "Serene", "Serial", "Server",
    "Settle", "Shadow", "Shaft", "Shake", "Shape",
    "Share", "Shark", "Shave", "Shawl", "Shed",
    "Sheep", "Sheet", "Shelf", "Shell", "Shelter",
    "Shield", "Shift", "Shine", "Ship", "Shirt",
    "Shock", "Shoe", "Shop", "Shore", "Shot",
    "Shovel", "Show", "Shower", "Shrimp", "Shrine",
    "Shrub", "Shuffle", "Sibling", "Side", "Siege",
    "Sight", "Sign", "Signal", "Silence", "Silk",
    "Silver", "Singer", "Sink", "Siren", "Sister",
    "Skate", "Skeleton", "Sketch", "Skill", "Skin",
    "Skip", "Skirt", "Skull", "Sky", "Slab",
    "Slate", "Sled", "Sleep", "Sleeve", "Slice",
    "Slide", "Sling", "Slip", "Slope", "Slot",
    "Smash", "Smell", "Smile", "Smoke", "Snack",
    "Snail", "Snake", "Snap", "Snare", "Snarl",
    "Sneak", "Sniff", "Snow", "Soap", "Soar",
    "Sock", "Socket", "Soda", "Sofa", "Soil",
    "Solar", "Soldier", "Solid", "Sonar", "Song",
    "Sorbet", "Sort", "Soul", "Sound", "Soup",
    "Sour", "Source", "South", "Space", "Spade",
    "Span", "Spare", "Spark", "Sparrow", "Spear",
    "Speed", "Spell", "Sphere", "Spice", "Spider",
    "Spill", "Spin", "Spine", "Spire", "Spirit",
    "Splash", "Split", "Spoke", "Sponge", "Spoon",
    "Sport", "Spot", "Spray", "Spring", "Sprout",
    "Spruce", "Spur", "Square", "Squash", "Squid",
    "Squirrel", "Stable", "Stack", "Stadium", "Staff",
    "Stage", "Stain", "Stair", "Stake", "Stalk",
    "Stall", "Stamp", "Stand", "Staple", "Star",
    "Stare", "Start", "State", "Status", "Stay",
    "Steak", "Steal", "Steam", "Steel", "Steep",
    "Steer", "Stem", "Step", "Sterling", "Stick",
    "Stiff", "Still", "Sting", "Stitch", "Stock",
    "Stomach", "Stone", "Stool", "Stop", "Store",
    "Storm", "Story", "Stove", "Strand", "Strap",
    "Straw", "Stream", "Street", "Stretch", "Strike",
    "String", "Strip", "Stroke", "Strong", "Studio",
    "Study", "Stump", "Stunt", "Style", "Substance",
    "Subtle", "Suburb", "Sugar", "Suit", "Sulfur",
    "Summer", "Summit", "Sun", "Sunset", "Supply",
    "Surf", "Surge", "Survey", "Sushi", "Swallow",
    "Swamp", "Swan", "Swap", "Swarm", "Sway",
    "Sweat", "Sweep", "Sweet", "Swell", "Swift",
    "Swim", "Swing", "Swirl", "Switch", "Sword",
    "Symbol", "Syrup",
    "Table", "Tablet", "Tack", "Tackle", "Tag",
    "Tail", "Tale", "Talent", "Talk", "Tank",
    "Tap", "Tape", "Target", "Task", "Taste",
    "Tavern", "Tea", "Teach", "Team", "Tear",
    "Temple", "Tenant", "Tender", "Tennis", "Tent",
    "Term", "Terrace", "Terrain", "Test", "Text",
    "Theater", "Theme", "Theory", "Thermal", "Thicket",
    "Thief", "Thimble", "Thing", "Think", "Thorn",
    "Thread", "Thrill", "Throat", "Throne", "Thunder",
    "Ticket", "Tide", "Tiger", "Tile", "Timber",
    "Time", "Tin", "Tip", "Tire", "Tissue",
    "Title", "Toast", "Token", "Toll", "Tomato",
    "Tomb", "Tone", "Tongue", "Tool", "Tooth",
    "Top", "Topic", "Torch", "Tornado", "Torque",
    "Tortoise", "Total", "Touch", "Tour", "Towel",
    "Tower", "Town", "Toy", "Trace", "Track",
    "Trade", "Trail", "Train", "Trait", "Trap",
    "Trash", "Travel", "Tray", "Treasure", "Treat",
    "Treaty", "Tree", "Trek", "Tremor", "Trend",
    "Trial", "Triangle", "Tribe", "Tribute", "Trick",
    "Trigger", "Trim", "Trip", "Triple", "Triumph",
    "Troop", "Trophy", "Tropic", "Trout", "Truck",
    "Trunk", "Trust", "Truth", "Try", "Tub",
    "Tube", "Tuck", "Tulip", "Tumble", "Tuna",
    "Tune", "Tunnel", "Turkey", "Turn", "Turnip",
    "Turtle", "Tusk", "Tutor", "Tweed", "Twig",
    "Twilight", "Twin", "Twist", "Type",
    "Umbrella", "Uncle", "Unicorn", "Unit", "Unity",
    "Universe", "Update", "Upper", "Urban", "Urn",
    "Usher", "Utility",
    "Vacuum", "Valley", "Valor", "Value", "Valve",
    "Van", "Vane", "Vapor", "Vase", "Vault",
    "Vector", "Veil", "Vein", "Velvet", "Vendor",
    "Venom", "Venture", "Verge", "Verse", "Version",
    "Vertex", "Vessel", "Vest", "Veteran", "Veto",
    "Vial", "Vibrant", "Vice", "Victor", "Video",
    "View", "Village", "Vine", "Vintage", "Violet",
    "Violin", "Viper", "Virgin", "Visa", "Visit",
    "Vista", "Visual", "Vital", "Vivid", "Vocal",
    "Voice", "Void", "Volcano", "Volume", "Vortex",
    "Vote", "Voucher", "Voyage", "Voyager",
    "Wade", "Waffle", "Wagon", "Waist", "Wait",
    "Wake", "Walk", "Wall", "Wallet", "Walnut",
    "Waltz", "Wander", "Ward", "Warden", "Warm",
    "Warp", "Warrior", "Wasp", "Watch", "Water",
    "Wave", "Wax", "Wealth", "Weapon", "Wear",
    "Weasel", "Weather", "Weave", "Web", "Wedge",
    "Weed", "Weight", "Welcome", "Weld", "Welfare",
    "Well", "West", "Whale", "Wharf", "Wheat",
    "Wheel", "Whip", "Whirl", "Whisper", "Whistle",
    "Wick", "Widow", "Width", "Wild", "Willow",
    "Wind", "Window", "Wine", "Wing", "Wink",
    "Winter", "Wipe", "Wire", "Wisdom", "Wish",
    "Wisp", "Witness", "Wolf", "Woman", "Wonder",
    "Wood", "Woods", "Wool", "Word", "Work",
    "World", "Worm", "Worry", "Worth", "Wound",
    "Wrap", "Wreath", "Wreck", "Wrench", "Wrist",
    "Write",
    "Yacht", "Yard", "Yarn", "Year", "Yeast",
    "Yellow", "Yelp", "Yield", "Yoga", "Yogurt",
    "Yolk", "Young", "Youth",
    "Zebra", "Zen", "Zero", "Zinc", "Zone",
    "Zoo",
]

def generate_passcode() -> str:
    # 5 words + 2-digit number. Entropy = 1668^5 * 90 ≈ 57 bits.
    # 5 is the minimum word count for adequate security given no password rotation.
    selected_words = [random.choice(WORDS) for _ in range(5)]
    number = random.randint(10, 99)
    return "".join(selected_words) + str(number)
